server :
  port : 8912
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: springboot.sm.domain

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/sm?useSSL=false
    username: root
  mail:
    host: smtp.gmail.com
    port: 587
    username: username1
    password: password1
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000




file:
  dir: C:/upload-test-folder/

