server :
  port : 8912

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: springboot.sm.domain

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/sm?useSSL=false
    username: root

file:
  dir: C:/upload-test-folder/
